# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending Approval"),
                            ("ENR", "Enrolled"),
                            ("DRP", "Dropped"),
                            ("TRF", "Transferred"),
                            ("GRD", "Graduated"),
                            ("WDN", "Withdrawn"),
                            ("LV", "On Leave"),
                            ("SUS", "Suspended"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending Approval"),
                            ("ENR", "Enrolled"),
                            ("DRP", "Dropped"),
                            ("TRF", "Transferred"),
                            ("GRD", "Graduated"),
                            ("WDN", "Withdrawn"),
                            ("LV", "On Leave"),
                            ("SUS", "Suspended"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIN", "Financial"),
                            ("ACD", "Academic Difficulty"),
                            ("PRS", "Personal"),
                            ("TRF", "Transfer to Another School"),
                            ("HLT", "Health"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentHold",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectEnrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_dropped", models.BooleanField(default=False)),
                ("drop_date", models.DateField(blank=True, null=True)),
                ("drop_reason", models.CharField(blank=True, max_length=10)),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["enrollment", "subject__code"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending Approval"),
                            ("ENR", "Enrolled"),
                            ("DRP", "Dropped"),
                            ("TRF", "Transferred"),
                            ("GRD", "Graduated"),
                            ("WDN", "Withdrawn"),
                            ("LV", "On Leave"),
                            ("SUS", "Suspended"),
                        ],
                        default="PND",
                        max_length=10,
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNP", "Unpaid"),
                            ("PRT", "Partially Paid"),
                            ("PD", "Fully Paid"),
                            ("SCH", "Covered by Scholarship"),
                        ],
                        default="UNP",
                        max_length=10,
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, help_text="If transferee", max_length=200
                    ),
                ),
                (
                    "lrn",
                    models.CharField(
                        blank=True, help_text="Learner Reference Number", max_length=20
                    ),
                ),
                (
                    "drop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIN", "Financial"),
                            ("ACD", "Academic Difficulty"),
                            ("PRS", "Personal"),
                            ("TRF", "Transfer to Another School"),
                            ("HLT", "Health"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("drop_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="classes.academicyear",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="classes.gradelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
            },
        ),
    ]
