# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FTH", "Father"),
                            ("MTH", "Mother"),
                            ("GRD", "Legal Guardian"),
                            ("GRP", "Grandparent"),
                            ("SIB", "Sibling"),
                            ("STP", "Step-parent"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("lives_with_student", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["student", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=3,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="List of allergies"),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, help_text="Asthma, diabetes, etc."),
                ),
                (
                    "medications",
                    models.TextField(blank=True, help_text="Regular medications"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "health_insurance_provider",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "health_insurance_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("physician_name", models.CharField(blank=True, max_length=100)),
                ("physician_contact", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("student_id", models.CharField(max_length=50, unique=True)),
                (
                    "lrn",
                    models.CharField(
                        blank=True, help_text="Learner Reference Number", max_length=20
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("birth_place", models.CharField(blank=True, max_length=200)),
                ("nationality", models.CharField(default="Filipino", max_length=100)),
                ("religion", models.CharField(blank=True, max_length=100)),
                ("current_address", models.TextField()),
                ("permanent_address", models.TextField(blank=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("TRF", "Transferred"),
                            ("GRD", "Graduated"),
                            ("DRP", "Dropped"),
                            ("LV", "On Leave"),
                        ],
                        default="ACT",
                        max_length=10,
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                ("profile_picture_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentAchievement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("awarding_body", models.CharField(max_length=200)),
                ("date_awarded", models.DateField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SCHOOL", "School Level"),
                            ("DISTRICT", "District Level"),
                            ("DIVISION", "Division Level"),
                            ("REGIONAL", "Regional Level"),
                            ("NATIONAL", "National Level"),
                            ("INTERNATIONAL", "International Level"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("certificate_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-date_awarded"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PSA_BIRTH", "PSA Birth Certificate"),
                            ("REPORT_CARD", "Report Card (SF9)"),
                            ("GOOD_MORAL", "Good Moral Character"),
                            ("TRANSFER", "Transfer Credentials"),
                            ("MEDICAL", "Medical Certificate"),
                            ("ID_PICTURE", "2x2 ID Picture"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
