# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graduation_year",
                    models.IntegerField(help_text="Year of graduation"),
                ),
                (
                    "batch",
                    models.CharField(
                        blank=True, help_text="e.g., Batch 2020", max_length=20
                    ),
                ),
                ("current_city", models.CharField(blank=True, max_length=100)),
                (
                    "current_country",
                    models.CharField(default="Philippines", max_length=100),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True,
                        help_text="Personal email (not school email)",
                        max_length=254,
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether alumni engages with the school"
                    ),
                ),
            ],
            options={
                "ordering": ["-graduation_year", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniAchievement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Top 10 Under 40, Best Thesis Award",
                        max_length=200,
                    ),
                ),
                ("awarding_body", models.CharField(max_length=200)),
                ("date_received", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("certificate_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="AlumniEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True)),
                ("registration_deadline", models.DateTimeField()),
            ],
            options={
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SCH", "Scholarship Fund"),
                            ("BLD", "Building Fund"),
                            ("GEN", "General Fund"),
                            ("EVT", "Event Sponsorship"),
                            ("EQP", "Equipment"),
                        ],
                        default="GEN",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("SE", "Self-employed"),
                            ("CT", "Contractual"),
                            ("IN", "Internship"),
                            ("UN", "Unemployed"),
                        ],
                        default="FT",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rsvp_status",
                    models.CharField(
                        choices=[
                            ("GO", "Going"),
                            ("NG", "Not Going"),
                            ("MB", "Maybe"),
                            ("NR", "No Response"),
                        ],
                        default="NR",
                        max_length=10,
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostGraduateEducation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g., BS Computer Science", max_length=200
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("year_start", models.IntegerField()),
                ("year_end", models.IntegerField(blank=True, null=True)),
                ("is_graduate", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-year_end"],
            },
        ),
    ]
