# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alumni_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumniachievement",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="alumni.alumni",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="alumni.alumni",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to="alumni.alumni",
            ),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendances",
                to="alumni.alumni",
            ),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="alumni.alumnievent",
            ),
        ),
        migrations.AddField(
            model_name="postgraduateeducation",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="higher_educations",
                to="alumni.alumni",
            ),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(
                fields=["graduation_year"], name="alumni_alum_graduat_36e3a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(fields=["batch"], name="alumni_alum_batch_80392e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventattendance",
            unique_together={("alumni", "event")},
        ),
    ]
