# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.choice",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="assessments.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assessments.question"
            ),
        ),
        migrations.AddField(
            model_name="rubriccriterion",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_criteria",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="rubriclevel",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="assessments.rubriccriterion",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assessments.assessment",
            ),
        ),
    ]
