# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_submissions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="assessmentgrade",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_record",
                to="assessments.submission",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assessments.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["subject", "is_published"],
                name="assessments_subject_e38ecc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["due_date"], name="assessments_due_dat_4823c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["assessment", "order"], name="assessments_assessm_815df6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="choice",
            unique_together={("question", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("assessment", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "question")},
        ),
    ]
