# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 2025-2026", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("room_number", models.CharField(max_length=20, unique=True)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=30)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CR", "Regular Classroom"),
                            ("LB", "Laboratory"),
                            ("AD", "Auditorium"),
                            ("GY", "Gymnasium"),
                            ("LR", "Library"),
                            ("OF", "Office"),
                        ],
                        default="CR",
                        max_length=10,
                    ),
                ),
                ("has_projector", models.BooleanField(default=False)),
                ("has_aircon", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("K", "Kindergarten"),
                            ("G1", "Grade 1"),
                            ("G2", "Grade 2"),
                            ("G3", "Grade 3"),
                            ("G4", "Grade 4"),
                            ("G5", "Grade 5"),
                            ("G6", "Grade 6"),
                            ("G7", "Grade 7"),
                            ("G8", "Grade 8"),
                            ("G9", "Grade 9"),
                            ("G10", "Grade 10"),
                            ("G11", "Grade 11"),
                            ("G12", "Grade 12"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="e.g., Grade 7", max_length=50)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="1=K, 2=G1, ... 13=G12", unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("SEM", "Semester"),
                            ("QTR", "Quarter"),
                            ("TRI", "Trimester"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        help_text="1 for first semester/quarter, 2 for second, etc."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., First Semester, Quarter 1", max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["academic_year", "term_number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., A, B, 1, St. Luke", max_length=20
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=40)),
                ("current_enrollment", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="classes.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="classes.classroom",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="classes.gradelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["grade_level__order", "name"],
            },
        ),
    ]
