# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_sections",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="If section is term-specific (e.g., summer class)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="classes.term",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("academic_year", "term_type", "term_number")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("name", "grade_level", "academic_year")},
        ),
    ]
