# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField(blank=True)),
                ("number_of_floors", models.PositiveSmallIntegerField(default=1)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FacilityReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("purpose", models.TextField()),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending Approval"),
                            ("APP", "Approved"),
                            ("REJ", "Rejected"),
                            ("CNC", "Cancelled"),
                            ("CMP", "Completed"),
                        ],
                        default="PND",
                        max_length=10,
                    ),
                ),
                ("attendees_count", models.PositiveIntegerField(default=0)),
                ("requires_setup", models.BooleanField(default=False)),
                ("setup_notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="FacilityUsageLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("condition_before", models.CharField(blank=True, max_length=100)),
                ("condition_after", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MED", "Medium"),
                            ("HIGH", "High"),
                            ("URG", "Urgent"),
                        ],
                        default="MED",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("INP", "In Progress"),
                            ("CMP", "Completed"),
                            ("CNC", "Cancelled"),
                        ],
                        default="PND",
                        max_length=10,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("BLD", "Building"),
                            ("CR", "Classroom"),
                            ("LAB", "Laboratory"),
                            ("LIB", "Library"),
                            ("AUD", "Auditorium"),
                            ("GYM", "Gymnasium"),
                            ("OFF", "Office"),
                            ("CAN", "Canteen"),
                            ("RST", "Restroom"),
                            ("PRK", "Parking"),
                            ("FLD", "Sports Field"),
                        ],
                        max_length=10,
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVL", "Available"),
                            ("OCC", "Occupied"),
                            ("MNT", "Under Maintenance"),
                            ("RSV", "Reserved"),
                            ("CLS", "Closed"),
                        ],
                        default="AVL",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g., ['projector', 'aircon', 'wifi']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="facilities.building",
                    ),
                ),
            ],
            options={
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("NEEDS_REPAIR", "Needs Repair"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("RETIRED", "Retired"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
