# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "total_collections",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_assessments",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("payment_method_breakdown", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PCT", "Percentage"), ("FXD", "Fixed Amount")],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage or fixed amount",
                        max_digits=8,
                    ),
                ),
                ("is_percentage", models.BooleanField(default=True)),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition Only"),
                            ("ALL_FEES", "All Fees"),
                            ("SPECIFIC", "Specific Fee Category"),
                        ],
                        default="TUITION",
                        max_length=20,
                    ),
                ),
                (
                    "specific_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TUI", "Tuition Fee"),
                            ("LAB", "Laboratory Fee"),
                            ("LIB", "Library Fee"),
                            ("COM", "Computer Fee"),
                            ("SPT", "Sports Fee"),
                            ("MED", "Medical/Dental Fee"),
                            ("GUID", "Guidance Fee"),
                            ("SO", "Student Organization Fee"),
                            ("INS", "Insurance"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeeAssessment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("PRT", "Partially Paid"),
                            ("PD", "Fully Paid"),
                            ("OVD", "Overdue"),
                            ("CNC", "Cancelled"),
                        ],
                        default="PND",
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Tuition Fee Grade 7, Laboratory Fee STEM",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TUI", "Tuition Fee"),
                            ("LAB", "Laboratory Fee"),
                            ("LIB", "Library Fee"),
                            ("COM", "Computer Fee"),
                            ("SPT", "Sports Fee"),
                            ("MED", "Medical/Dental Fee"),
                            ("GUID", "Guidance Fee"),
                            ("SO", "Student Organization Fee"),
                            ("INS", "Insurance"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "is_per_semester",
                    models.BooleanField(default=True, help_text="If false, annual fee"),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["academic_year", "grade_level", "category"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField()),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHECK", "Check"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("ONLINE", "Online Payment"),
                            ("CARD", "Debit/Credit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("check_number", models.CharField(blank=True, max_length=50)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("ACD", "Academic Scholarship"),
                            ("ATH", "Athletic Scholarship"),
                            ("NED", "Need-Based"),
                            ("GOV", "Government Grant"),
                            ("PRV", "Private Grant"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grantor",
                    models.CharField(
                        blank=True, help_text="Organization or donor", max_length=200
                    ),
                ),
                ("awarded_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_renewable", models.BooleanField(default=False)),
                ("terms", models.TextField(blank=True)),
            ],
        ),
    ]
