# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("classes", "0002_initial"),
        ("enrollments", "0002_initial"),
        ("fees", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionreport",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assessments",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assessments",
                to="classes.term",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="academic.academicprogram",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="classes.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="fees.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="fees.feeassessment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarships",
                to="fees.discount",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarships",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionreport",
            unique_together={("report_date",)},
        ),
        migrations.AlterUniqueTogether(
            name="feeassessment",
            unique_together={("enrollment", "fee_structure", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="scholarship",
            unique_together={("student", "discount", "awarded_date")},
        ),
    ]
