# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_attendances",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="hr.payrollperiod",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.position",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together={("employee", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("employee", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("title", "department")},
        ),
    ]
