# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("enrollments", "0001_initial"),
        ("grades", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalgrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_grades",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="finalgrade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="final_grades",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="enrollments.enrollment",
            ),
        ),
    ]
