# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("classes", "0002_initial"),
        ("grades", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="classes.term",
            ),
        ),
        migrations.AddField(
            model_name="gradecomponent",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_components",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="gradecomponent",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_components",
                to="classes.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="gradecomponent",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_components",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="classes.term",
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcript",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="finalgrade",
            unique_together={("student", "subject", "enrollment")},
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "subject", "enrollment", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="gradecomponent",
            unique_together={("subject", "academic_year", "grade_level", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student", "academic_year", "term")},
        ),
    ]
