from .test_academic_year import AcademicYearModelTest, AcademicYearServiceTest, AcademicYearSerializerTest
from .test_term import TermModelTest, TermServiceTest, TermSerializerTest
from .test_grade_level import GradeLevelModelTest, GradeLevelServiceTest, GradeLevelSerializerTest
from .test_classroom import ClassroomModelTest, ClassroomServiceTest, ClassroomSerializerTest
from .test_section import SectionModelTest, SectionServiceTest, SectionSerializerTest