# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("teacher_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birth_date", models.DateField()),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("LV", "On Leave"),
                            ("RES", "Resigned"),
                            ("TER", "Terminated"),
                        ],
                        default="ACT",
                        max_length=10,
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("VS", "Visiting"),
                            ("PR", "Practicum Teacher"),
                        ],
                        default="FT",
                        max_length=10,
                    ),
                ),
                (
                    "highest_degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BS", "Bachelor's Degree"),
                            ("MA", "Master's Degree"),
                            ("PHD", "Doctorate"),
                            ("DIP", "Diploma"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("years_of_experience", models.PositiveSmallIntegerField(default=0)),
                ("profile_picture_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherQualification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualification_name",
                    models.CharField(
                        help_text="e.g., LET Passer, Masteral Units", max_length=200
                    ),
                ),
                ("issuing_body", models.CharField(max_length=200)),
                ("date_earned", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("attachment_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-date_earned"],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialized_teachers",
                        to="academic.subject",
                    ),
                ),
            ],
        ),
    ]
