# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("classes", "0002_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specializations",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacherqualification",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="classes.section",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.term",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="specialization",
            unique_together={("teacher", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="teachingassignment",
            unique_together={("teacher", "section", "subject", "academic_year")},
        ),
    ]
