# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("BLK", "Blacklisted"),
                        ],
                        default="ACT",
                        max_length=10,
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("alternative_contact", models.CharField(blank=True, max_length=20)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Personal email (different from user email)",
                        max_length=254,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("employer", models.CharField(blank=True, max_length=200)),
                ("employer_address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                ("receive_notifications", models.BooleanField(default=True)),
                ("receive_email_digest", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ParentCommunicationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("CALL", "Phone Call"),
                            ("IN_PERSON", "In Person"),
                            ("PORTAL", "Parent Portal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INCOMING", "Incoming"), ("OUTGOING", "Outgoing")],
                        max_length=10,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FTH", "Father"),
                            ("MTH", "Mother"),
                            ("GRD", "Legal Guardian"),
                            ("GRP", "Grandparent"),
                            ("SIB", "Sibling"),
                            ("STP", "Step-parent"),
                            ("OTH", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True, help_text="Allowed to pick up student from school"
                    ),
                ),
                ("receives_academic_updates", models.BooleanField(default=True)),
                ("receives_disciplinary_updates", models.BooleanField(default=True)),
                ("receives_payment_reminders", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["student", "-is_primary_contact"],
            },
        ),
    ]
