# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicProgram",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("JHS", "Junior High School (Grades 7-10)"),
                            ("SHS", "Senior High School (Grades 11-12)"),
                            ("COL", "College"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["level", "code"],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("K", "Kindergarten"),
                            ("G1", "Grade 1"),
                            ("G2", "Grade 2"),
                            ("G3", "Grade 3"),
                            ("G4", "Grade 4"),
                            ("G5", "Grade 5"),
                            ("G6", "Grade 6"),
                            ("G7", "Grade 7"),
                            ("G8", "Grade 8"),
                            ("G9", "Grade 9"),
                            ("G10", "Grade 10"),
                            ("G11", "Grade 11"),
                            ("G12", "Grade 12"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "year_effective",
                    models.IntegerField(
                        help_text="School year when this curriculum takes effect, e.g., 2025"
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="academic.academicprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_program", "grade_level", "-year_effective"],
                "unique_together": {
                    ("academic_program", "grade_level", "year_effective")
                },
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., MATH101", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="e.g., Algebra", max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "units",
                    models.DecimalField(decimal_places=1, default=3.0, max_digits=4),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("CORE", "Core Subject"),
                            ("APP", "Applied Subject"),
                            ("SPEC", "Specialized Subject"),
                            ("ELEC", "Elective"),
                        ],
                        default="CORE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="academic_su_code_d89c14_idx"),
                    models.Index(
                        fields=["is_active"], name="academic_su_is_acti_4e0783_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_optional", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "required_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_for",
                        to="academic.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites_required",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject", "required_subject")},
            },
        ),
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_outcomes",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order"],
                "unique_together": {("subject", "code")},
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1ST", "First Semester"),
                            ("2ND", "Second Semester"),
                            ("SUM", "Summer"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "year_level_order",
                    models.PositiveSmallIntegerField(
                        help_text="1 for 1st year, 2 for 2nd year, etc."
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="Order within semester/year"
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="academic.curriculum",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["curriculum", "year_level_order", "semester", "sequence"],
                "unique_together": {("curriculum", "subject")},
            },
        ),
    ]
