# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("RC", "Report Card"),
                            ("TR", "Transcript of Records"),
                            ("AT", "Attendance Summary"),
                            ("FS", "Financial Statement"),
                            ("GS", "Grade Sheet"),
                            ("CR", "Collection Report"),
                            ("ER", "Enrollment Report"),
                            ("CU", "Custom Report"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("XLSX", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending Generation"),
                            ("PRC", "Processing"),
                            ("CMP", "Completed"),
                            ("FLD", "Failed"),
                        ],
                        default="PND",
                        max_length=10,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Filters used (e.g., {'academic_year': '2025-2026', 'grade_level': 'G7'})",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="Storage URL of generated file"
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("DOWNLOADED", "Downloaded"),
                            ("EMAILED", "Emailed"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("RC", "Report Card"),
                            ("TR", "Transcript of Records"),
                            ("AT", "Attendance Summary"),
                            ("FS", "Financial Statement"),
                            ("GS", "Grade Sheet"),
                            ("CR", "Collection Report"),
                            ("ER", "Enrollment Report"),
                            ("CU", "Custom Report"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("XLSX", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="e.g., '0 8 * * 1' for every Monday 8 AM",
                        max_length=100,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, help_text="List of email addresses"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PND", "Pending Generation"),
                            ("PRC", "Processing"),
                            ("CMP", "Completed"),
                            ("FLD", "Failed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("RC", "Report Card"),
                            ("TR", "Transcript of Records"),
                            ("AT", "Attendance Summary"),
                            ("FS", "Financial Statement"),
                            ("GS", "Grade Sheet"),
                            ("CR", "Collection Report"),
                            ("ER", "Enrollment Report"),
                            ("CU", "Custom Report"),
                        ],
                        max_length=10,
                    ),
                ),
                ("template_file", models.FileField(upload_to="report_templates/")),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["report_type", "name"],
            },
        ),
    ]
