# Generated by Django 5.2.3 on 2026-04-22 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                ("is_school_wide", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PR", "Present"),
                            ("AB", "Absent"),
                            ("LT", "Late"),
                            ("EX", "Excused"),
                            ("HD", "Holiday"),
                            ("NC", "No Class"),
                        ],
                        default="PR",
                        max_length=10,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("late_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "late_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TR", "Traffic"),
                            ("PR", "Personal Matter"),
                            ("SK", "Sick"),
                            ("OT", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.CharField(max_length=20)),
                ("total_present", models.PositiveIntegerField(default=0)),
                ("total_absent", models.PositiveIntegerField(default=0)),
                ("total_late", models.PositiveIntegerField(default=0)),
                ("total_excused", models.PositiveIntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PR", "Present"),
                            ("AB", "Absent"),
                            ("LT", "Late"),
                            ("EX", "Excused"),
                            ("HD", "Holiday"),
                            ("NC", "No Class"),
                        ],
                        default="PR",
                        max_length=10,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("late_minutes", models.PositiveSmallIntegerField(default=0)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date", "teacher__last_name"],
            },
        ),
    ]
