# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("attendance", "0002_initial"),
        ("classes", "0002_initial"),
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendances",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="classes.section",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="studentattendancesummary",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="studentattendancesummary",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_summaries",
                to="students.student",
            ),
        ),
    ]
