# Generated by Django 5.2.3 on 2026-04-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0003_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherattendance",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_teacher_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherattendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="teachers.teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_514473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student", "academic_year"],
                name="attendance__student_8c72fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["section", "date"], name="attendance__section_1bf128_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "subject", "date", "section")},
        ),
        migrations.AlterUniqueTogether(
            name="studentattendancesummary",
            unique_together={("student", "academic_year", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="teacherattendance",
            unique_together={("teacher", "date")},
        ),
    ]
